### ISSUE TITLE
DeprecationWarnings for formatargspec and collections in python3.7

### ISSUE THREAD

**Issue by Attryy** [nltk/nltk#2338]
Hi there, I was upgrading python2.7 to python3.7. When running pytests, bunch of warnings pop up from nltk library. 

Line 68 in decorators.py
`DeprecationWarning: 'formatargspec' is deprecated since Python 3.5. Use 'signature' and the 'Signature' object directly` 

Line 15 in counter.py and line 13 in vocabulary.py
`DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working`

**Comment by alvations** [comment]
Patched from #2364

**Comment by asevans48** [comment]
So, this doesn't seem resolved from the pypi version 1.12.0. Is this correct? I use pytest and receive the same warnings. Is this secure?

**Comment by alvations** [comment]
@asevans48 This should have been patched by #2364 on the develop branch. The next version of the NLTK release should be "pip-able" soon =)

Closed issues usually means it's solved in the `develop` branch of the code and not the release. Sorry for the confusion.

**Comment by bbookman** [comment]
Still getting this issue as of 3.4.5 released Aug of 2019.  Please release this fix!  Is there a method of suppressing the warning?

**Comment by bbookman** [comment]
> @asevans48 This should have been patched by #2364 on the develop branch. The next version of the NLTK release should be "pip-able" soon =)
> 
> Closed issues usually means it's solved in the `develop` branch of the code and not the release. Sorry for the confusion.

Not yet released from my experience with 3.4.5
