### ISSUE TITLE
"from nltk import util" imports nltk.cluster.util instead of nltk.util

### ISSUE THREAD

**Issue by dan-blanchard** [nltk/nltk#238]
I have a lot of code that uses the `util.ngrams` iterator, and I noticed that after the latest release I kept getting `AttributeError: 'module' object has no attribute 'ngrams'` errors all over the place. It turns out that in the latest release when you try to import the `nltk.util` module, it actually imports the `nltk.cluster.util` now. You can actually get around this by directly importing the functions you want like `from nltk.util import ngrams`, but it'd be really nice if it went back to the way it was before.

**Comment by stevenbird** [comment]
The problem is caused by line 154 of nltk/**init**.py, which imports \* from nltk.cluster.  These global imports should really go away (except that many of the book examples would break).  I tried defining **all** in nltk/cluster/**init**.py but this didn't solve the problem.  cf http://docs.python.org/tutorial/modules.html#importing-from-a-package

**Comment by stevenbird** [comment]
Resolved in https://github.com/nltk/nltk/commit/c3d4033259181e9ecad07a35f1eedb0467d2d229

**Comment by WGH-** [comment]
Is it really resolved? I can reproduce in NLTK 3.0.0 on both Python 2.7 and Python 3.3.

**Comment by maxlemieux** [comment]
Confirmed this is still a problem in current release. I reproduced on Python 2.7, NLTK 3.0.2.

Direct import works as mentioned. Accessing by nltk.util.ngrams does not work.
