### ISSUE TITLE
Old functions in use in util.py

### ISSUE THREAD

**Issue by Pinkertoncito** [nltk/nltk#249]
What version of NLTK are you using?  (See nltk.**version**).  Please only
submit bug reports for the current version.

Hi, I am using '2.0b9' from Ubuntu, but I checked that these errors were also in the latest version for download (2.01rc1).

What steps will reproduce the problem?  (e.g. include Python source code)

Using SVD dimension reduction reproduces the errors.

clusterer = cluster.KMeansClusterer(2, euclidean_distance, repeats=10,svd_dimensions=3)
print clusterer.cluster(numpy.array(vectors), True)

What is the expected output? What do you see instead?

The problem is that util.py reports various errors.  The first one is fixed (explicit loading of numpy.array), but furthermore cluster/util.py refers to the numpy.Float64 which should be numpy.float64 and numpy.matrixmultiply which is gone (previously deprecated from numpy).

**Comment by xim** [comment]
Hopefully fixed in commit 2638b7aa16385aa6bcf14c609651e3199edce688. No idea what array sizes I should have used, but the following code now runs.

> > > import numpy, random, nltk
> > > a = numpy.array([[random.randint(0,1) for _ in xrange(3)] for _ in xrange(3)])
> > > clusterer = nltk.cluster.KMeansClusterer(2, nltk.cluster.euclidean_distance, repeats=10,svd_dimensions=3)
> > > clusterer.cluster(a, True)
> > > None [[1 0 0]
> > >  [1 1 1]
> > >  [0 1 1]]
> > > [0, 1, 1]

**Comment by Pinkertoncito** [comment]
hi, I still don't think it works, because you need a dimensionality that is lower than the one in your array to test the dimensionality reduction.

test with:
a = numpy.array([[random.randint(0,1) for _ in xrange(10)] for _ in xrange(10)]) instead

ps: look at Issue #151  as well

**Comment by xim** [comment]
Keeping this issue closed, as imports are fixed. May have a look in a couple of weeks ;)
