### ISSUE TITLE
RegexpTagger AttributeError: 'RegexpTagger' object has no attribute '_regexps'

### ISSUE THREAD

**Issue by maxleonov** [nltk/nltk#287]
Hi,
I found that RegexpTagger (nltk/nltk/tag/sequential.py) refers to a property which currently does not exist. In **repr**() method it deals with non-existing property _regexps (which I assume used to store a list of regular expressions in previous versions). This results in the following error when trying to output an instance of this class as a string:
AttributeError: 'RegexpTagger' object has no attribute '_regexps'
(notice difference between _regexps and _regexs).
This is a small issue but anyway better be fixed.

**Comment by stevenbird** [comment]
Thanks for the bugfix -- this is resolved in https://github.com/nltk/nltk/commit/0bab3371a6d575616f8c8e27f55e2d21101dbc7e

**Comment by maxleonov** [comment]
Sorry for pointing this out, but it doesn't fix the issue.
self._regexs is not a list but a _sre.SRE_Pattern object
currently it raises "TypeError: object of type '_sre.SRE_Pattern' has no len()"

I think, in order not to store an extra list object in memory, the size could be stored directly in 

```
#in __init__() the size could be stored like this:
self._size=len(regexs)

#and then in __repr__() it can be used like this:
return '<Regexp Tagger: size=%d>' % self._size
```

**Comment by stevenbird** [comment]
Thanks for the fix.

**Comment by stevenbird** [comment]
Resolved in https://github.com/nltk/nltk/commit/96d8497288b172d0d0b0b3b991e47d0fc4891da9

**Comment by RinkeHoekstra** [comment]
`regexs` is not a defined variable in the **init** method. I've fixed this locally by using the length of `regexps` instead of `regexs`

**Comment by stevenbird** [comment]
Thanks, and I've now added a doctest to ensure that this is fixed at last.

**Comment by guizonatto** [comment]
Is this issue back in 3.5?
Exception has occurred: AttributeError
'RegexpTagger' object has no attribute '_regexps'

I am facing this same error when trying to tag a text.

**Comment by gustavo-machado-vc** [comment]
> Is this issue back in 3.5?

Yes, I've just run in both versions 3.4.5 and 3.5. There were no problems in 3.4.5 but in the newest version I faced the same error.

**Comment by yaalaa** [comment]
+1 - py 3.11.3, nltk==3.8.1

**Comment by tomaarsen** [comment]
@yaalaa I am unable to reproduce this:
```python
from nltk.corpus import brown
from nltk.tag import RegexpTagger
test_sent = brown.sents(categories='news')[0]
regexp_tagger = RegexpTagger(
    [(r'^-?[0-9]+(\.[0-9]+)?$', 'CD'),  # cardinal numbers
        (r'(The|the|A|a|An|an)$', 'AT'),   # articles
        (r'.*able$', 'JJ'),                # adjectives
        (r'.*ness$', 'NN'),                # nouns formed from adjectives
        (r'.*ly$', 'RB'),                  # adverbs
        (r'.*s$', 'NNS'),                  # plural nouns
        (r'.*ing$', 'VBG'),                # gerunds
        (r'.*ed$', 'VBD'),                 # past tense verbs
        (r'.*', 'NN')                      # nouns (default)
])
print(repr(regexp_tagger))
print(str(regexp_tagger))
print(regexp_tagger.tag(test_sent))
```
```
<Regexp Tagger: size=9>
<Regexp Tagger: size=9>
[('The', 'AT'), ('Fulton', 'NN'), ('County', 'NN'), ('Grand', 'NN'), ('Jury', 'NN'), ('said', 'NN'), ('Friday', 'NN'), ('an', 'AT'), ('investigation', 'NN'), ('of', 'NN'), ("Atlanta's", 'NNS'), ('recent', 'NN'), ('primary', 'NN'), ('election', 'NN'), ('produced', 'VBD'), ('``', 'NN'), ('no', 'NN'), ('evidence', 'NN'), ("''", 'NN'), ('that', 'NN'), ('any', 'NN'), ('irregularities', 'NNS'), ('took', 'NN'), ('place', 'NN'), ('.', 'NN')]
```
Are you certain that you are running `nltk==3.8.1`?

`self._regexps` is defined in the very first line of the `RegexpTagger` initializer.
https://github.com/nltk/nltk/blob/fc53edbf6f0763971afca5855386a2a382da37ac/nltk/tag/sequential.py#L541

- Tom Aarsen

**Comment by kelvindeephow** [comment]
I can confirm the same issue (AttributeError: 'RegexpTagger' object has no attribute '_regexps') is happening on python 3.8 with nltk==3.8.1. Only solution that worked was to downgrade to version 3.4.5. Here is the stack trace:
```
  File "/usr/local/lib/python3.8/site-packages/nltk/tag/brill.py", line 261, in tag
    tagged_tokens = self._initial_tagger.tag(tokens)
  File "/usr/local/lib/python3.8/site-packages/nltk/tag/sequential.py", line 61, in tag
    tags.append(self.tag_one(tokens, i, tags))
  File "/usr/local/lib/python3.8/site-packages/nltk/tag/sequential.py", line 81, in tag_one
    tag = tagger.choose_tag(tokens, index, history)
  File "/usr/local/lib/python3.8/site-packages/nltk/tag/sequential.py", line 559, in choose_tag
    for regexp, tag in self._regexps:
  AttributeError: 'RegexpTagger' object has no attribute '_regexps'
```
