### ISSUE TITLE
nltk.find:No such file or directory: '/root/nltk_data/tokenizers/punkt/PY3_tab'

### ISSUE THREAD

**Issue by hpx502766238** [nltk/nltk#3305]
nltk 3.8.1
```
import nltk
nltk.set_proxy('127.0.0.1:7890')
nltk.download('punkt_tab')
nltk.find('tokenizers/punkt_tab')

```
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.
Traceback (most recent call last):
  File "/mnt/vdb1/langchain-knowledge-base/1.py", line 4, in <module>
    nltk.find('tokenizers/punkt_tab')
  File "/mnt/vdb1/langchain-knowledge-base/venv/lib/python3.10/site-packages/nltk/data.py", line 537, in find
    return FileSystemPathPointer(p)
  File "/mnt/vdb1/langchain-knowledge-base/venv/lib/python3.10/site-packages/nltk/compat.py", line 41, in _decorator
    return init_func(*args, **kwargs)
  File "/mnt/vdb1/langchain-knowledge-base/venv/lib/python3.10/site-packages/nltk/data.py", line 312, in __init__
    raise OSError("No such file or directory: %r" % _path)
OSError: No such file or directory: '/root/nltk_data/tokenizers/punkt/PY3_tab'

**Comment by hpx502766238** [comment]
> nltk 3.8.1
> 
> ```
> import nltk
> nltk.set_proxy('127.0.0.1:7890')
> nltk.download('punkt_tab')
> nltk.find('tokenizers/punkt_tab')
> ```
> 
> [nltk_data] Downloading package punkt_tab to /root/nltk_data... [nltk_data] Unzipping tokenizers/punkt_tab.zip. Traceback (most recent call last): File "/mnt/vdb1/langchain-knowledge-base/1.py", line 4, in nltk.find('tokenizers/punkt_tab') File "/mnt/vdb1/langchain-knowledge-base/venv/lib/python3.10/site-packages/nltk/data.py", line 537, in find return FileSystemPathPointer(p) File "/mnt/vdb1/langchain-knowledge-base/venv/lib/python3.10/site-packages/nltk/compat.py", line 41, in _decorator return init_func(*args, **kwargs) File "/mnt/vdb1/langchain-knowledge-base/venv/lib/python3.10/site-packages/nltk/data.py", line 312, in **init** raise OSError("No such file or directory: %r" % _path) OSError: No such file or directory: '/root/nltk_data/tokenizers/punkt/PY3_tab'

I am sure the nltk_data was download successfully,but the PY3_tab folder indeed doesn't exist in the newest nltk_data.It seems that "find " method should be update,I use langchain UnstructedLoader,this check step is neccessary in langchain code.

**Comment by ekaf** [comment]
Punkt_tab cannot work with NLTK 3.8.1 for two reasons: 3.8.1 didn't have any handler for the new tab package, and it redirects the call to a PY3 directory to support the old pickles.

**Comment by naarkhoo** [comment]
when I do `nltk.download('punkt_tab')` I end up to `/root/nltk_data/tokenizers/punkt_tab` but I still get `OSError: No such file or directory: '/root/nltk_data/tokenizers/punkt/PY3_tab'` on the colab

**Comment by wastetime909** [comment]
Try upgrading upgrade nltk to the latest version (in my case, 3.9.1) solved the issue

**Comment by MostafaAhmed98** [comment]
to the people will see this error in the future, run this command line after installing NLTK library `pip install --upgrade nltk` it worked for me

**Comment by kaushalpowar** [comment]
Thanks @MostafaAhmed98  

`docs = loader.load()`
I was getting this error in Langchain while loding the data of code files.

**Comment by vivekk-promact** [comment]
I am using linux host with azure functions. getting the error 
No such file or directory: '/home/nltk_data/tokenizers/punkt/PY3_tab'

I tried upgrading as @MostafaAhmed98 mentioned. but same error occuring

**Comment by ekaf** [comment]
@vivekk-promact, if you are asked for a "PY3_tab" directory. it means that you are not using version 3.9.1 of NLTK. So the first step is to upgrade and ensure this first condition is met:

```
import nltk
print(nltk.__version__)
```
3.9.1

Then, if you hve not yet downloaded the _punkt_tab_ package:
`nltk.download('punkt_tab')`

Once you meet these two conditions, there should be no issue.

**Comment by vivekk-promact** [comment]
@ekaf I got to know that we were using OS level installing and also installing from the requirment.txt.

I checked both of them and now it is working thanks!

**Comment by maheshrajrp** [comment]
if you are using Google Colab,
running this should solve the issue.
`!pip install -U nltk`

**Comment by clashofphish** [comment]
I'm running version 3.9.1, but `nltk.find('tokenizer/punkt_tab', paths=nltk.data.path)` is still not working for me.

Here is my Python output where you can see `nltk.download('punkt_tab')` tells me that punkt_tab is already up-to-date, yet the `find` method still errors out.
```
Python 3.9.18 (main, Oct 15 2024, 22:21:30)
[Clang 15.0.0 (clang-1500.3.9.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import nltk
>>> nltk.__version__
'3.9.1'
>>> nltk.download('punkt_tab')
[nltk_data] Downloading package punkt_tab to
[nltk_data]     /Users/username/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
True
>>> nltk.find('tokenizer/punkt_tab', paths=nltk.data.path)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/username/.pyenv/versions/virtual-3.9.18/lib/python3.9/site-packages/nltk/data.py", line 579, in find
    raise LookupError(resource_not_found)
LookupError:
**********************************************************************
  Resource punkt_tab not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('punkt_tab')

  For more information see: https://www.nltk.org/data.html

  Attempted to load tokenizer/punkt_tab

  Searched in:
    - '/Users/username/nltk_data'
    - '/Users/username/.pyenv/versions/nlpHw3-3.9.18/nltk_data'
    - '/Users/username/.pyenv/versions/nlpHw3-3.9.18/share/nltk_data'
    - '/Users/username/.pyenv/versions/nlpHw3-3.9.18/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************
```

**Comment by iwanglei1** [comment]
有这个文件，但还是报错了：
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\iwang\\nltk_data\\tokenizers\\punkt_tab.zip\\punkt_tab\\english/collocations.tab'
